### ISSUE TITLE
Cache collisions for metric.RATE metrics

### ISSUE THREAD

**Issue by bryangwilliam** [newrelic/infra-integrations-sdk#48]
I am getting the following error from the sdk for the custom integration I am writing which uses the `metric.RATE` option:
```
WARN[0000] Error setting value: Samples for queue.jobsPerSecond are too close in time, skipping sampling 
WARN[0000] Error setting value: Samples for queue.jobsPerSecond are too close in time, skipping sampling 
WARN[0000] Error setting value: Samples for queue.jobsPerSecond are too close in time, skipping sampling 
```
The above example came from trying to add a metric named `queue.jobsPerSecond` to 4 different MetricSets. The problem seems to stem from the fact that names are global in the cache rather than being unique per MetricSet, which means that MetricSets which use the same metric name will have a collision.

Adding a unique prefix per MetricSet to the key would get rid of the problem.

##### Integrations SDK version

- [x] 2.0

##### Golang version

- [x] All of them

##### OS

- [x] All of them

**Comment by matiasburni** [comment]
Hi @bryangwilliam, we're going to take a look.

**Comment by varas** [comment]
Hi @bryangwilliam this issue should be fixed in the oncoming SDKv3 update  https://github.com/newrelic/infra-integrations-sdk/pull/106

So you can use `NewMetricSet(eventType string, nameSpacingAttributes ...metric.Attribute)` the optional list of attributes will namespace the metric, so they collision is avoided. See https://github.com/newrelic/infra-integrations-sdk/pull/106/files#diff-2fa204c6e91bc2d1cefbda792b92f384R82 

A usage sample could be: `NewSet("type", storeWrite, Attr("pod", "pod-a"))`
